### ISSUE TITLE
Program.ToString() does not return correct js content

### ISSUE THREAD

**Issue by ionuttamas** [sebastienros/esprima-dotnet#26] opened 2018-06-06 02:08 UTC
Doing:

`var program = new JavaScriptParser().Parse(js);
Assert.AreEqual(js, program.ToString())`

does not work. Is there a way to get the js text value from the program?

**Comment by lahma** [comment] 2018-06-18 18:07
Why don't you just keep a record of the js content you used to get the parsed version? Parsing produces AST which is quite hard to backtrack to original string format.

**Comment by sebastienros** [comment] 2018-08-11 00:43
Duplicate of #8

**Closed by sebastienros** 2018-08-11 00:43 UTC
